CREATE DATABASE CSE_3A_151;
USE CSE_3A_151;

CREATE TABLE BORROW (LOANNO INT,CNAME VARCHAR(50),BNAME VARCHAR(50),AMOUNT DECIMAL(8,2));

INSERT INTO BORROW (LOANNO,CNAME,BNAME,AMOUNT) VALUES (201,'ANIL','VRCE',1000.00);

INSERT INTO BORROW (LOANNO,CNAME,BNAME,AMOUNT) VALUES (206,'MEHUL','AJNI',5000.00);

INSERT INTO BORROW (LOANNO,CNAME,BNAME,AMOUNT) VALUES (311,'SUNIL','DHARAMPETH',3000.00);

INSERT INTO BORROW (LOANNO,CNAME,BNAME,AMOUNT) VALUES (321,'MADHURI','ANDHERI',2000.00);

INSERT INTO BORROW (LOANNO,CNAME,BNAME,AMOUNT) VALUES (375,'PRAMOD','VIRAR',8000.00);

INSERT INTO BORROW (LOANNO,CNAME,BNAME,AMOUNT) VALUES (481,'KRANTI','NEHRU PLACE',3000.00);

SELECT * FROM BORROW;